# Generated by Django 5.2.10 on 2026-01-26 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('tenants', '0002_remove_tenant_name_i18n_tenant_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assettype',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(help_text='The shipyard/tenant this asset belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='tenant',
        ),
    ]
