"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import urllib.parse
from pathlib import Path
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PUBLIC_DIR = BASE_DIR / "resources/public"
APPS_DIR = BASE_DIR / "apps"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-r05^86mriv&nwvs2uj2h0*radv4d)ozooaiuogp0^ekqni%9",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG") == "True"

ALLOWED_HOSTS = ["localhost", "127.0.0.1", os.environ.get("DOMAIN", "localhost")]
DOMAIN = os.environ.get("DOMAIN", "localhost")

CORS_ALLOWED_ORIGINS = [
    f"https://{DOMAIN}",
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    f"https://{DOMAIN}",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "corsheaders",
    "rest_framework",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.headless",
    "allauth.mfa",
    "allauth.socialaccount.providers.google",
    "allauth.usersessions",
    "django_celery_beat",
    "apps.tenants.apps.TenantsConfig",
    "apps.user.apps.UserConfig",
    "apps.notifications.apps.NotificationsConfig",
    "apps.assets.apps.AssetsConfig",
    "apps.settings.apps.SettingsConfig",
    "apps.platform_releases.apps.PlatformReleasesConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.tenants.middleware.TenantMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

REDIS_URL = os.environ.get("REDIS_URL", "redis://redis:6379/0")

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    url = urllib.parse.urlparse(DATABASE_URL)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": url.path[1:],
            "USER": url.username,
            "PASSWORD": url.password,
            "HOST": url.hostname,
            "PORT": url.port,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = PUBLIC_DIR / "static"

MEDIA_URL = "media/"
MEDIA_ROOT = PUBLIC_DIR / "media"

# WhiteNoise: compressed + hashed static files in production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
        if not DEBUG
        else "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "user.User"

# Allauth settings
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
SITE_ID = 1

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = True
ACCOUNT_LOGIN_BY_CODE_ENABLED = True
# ACCOUNT_ADAPTER = "apps.user.adapters.CustomAccountAdapter"
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_REAUTHENTICATION_TIMEOUT = 300
ACCOUNT_PASSWORD_RESET_BY_CODE_ENABLED = True
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

# MFA
MFA_PASSKEY_SIGNUP_ENABLED = True
MFA_PASSKEY_LOGIN_ENABLED = True
MFA_SUPPORTED_TYPES = ["totp", "recovery_codes", "webauthn"]
MFA_WEBAUTHN_RP_ID = DOMAIN
MFA_WEBAUTHN_RP_NAME = "MyProject"
MFA_ADAPTER = "apps.user.adapters.CustomMFAAdapter"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}

# Headless
HEADLESS_ADAPTER = "apps.user.adapters.CustomHeadlessAdapter"
HEADLESS_ONLY = True
HEADLESS_FRONTEND_URLS = {
    "browser": f"https://{DOMAIN}{{path}}",
    "account_confirm_email": f"https://{DOMAIN}/auth/email/confirm/{{key}}",
    "account_reset_password": f"https://{DOMAIN}/auth/reset-password",
    "account_reset_password_from_key": f"https://{DOMAIN}/auth/password/confirm/{{key}}",
    "account_signup": f"https://{DOMAIN}/register",
    "account_login": f"https://{DOMAIN}/login",
    "account_email": f"https://{DOMAIN}/account/email",
    "socialaccount_login_error": f"https://{DOMAIN}/account/provider/callback",
}


# CORS & CSRF
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    f"https://{DOMAIN}",
]
CORS_EXPOSE_HEADERS = ["X-CSRFToken"]
CORS_ALLOW_HEADERS = list(default_headers) + [
    "X-Password-Reset-Key",
    "X-Email-Verification-Key",
]

CSRF_TRUSTED_ORIGINS = [
    f"https://{DOMAIN}",
]

# Cookie settings (single-origin setup)
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_DOMAIN = None
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Email settings — SMTP config is loaded from the database at runtime
EMAIL_BACKEND = "apps.settings.email_backend.DatabaseEmailBackend"
DEFAULT_FROM_EMAIL = f"noreply@{DOMAIN}"


# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

CELERY_BEAT_SCHEDULE = {
    "send-broadcast-every-10-seconds": {
        "task": "apps.notifications.tasks.broadcast_heartbeat_notification",
        "schedule": 100.0,
    },
}
