# Generated by Django 5.2.10 on 2026-04-20 14:39

import apps.platform_releases.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(help_text='Free-form version label, e.g. v1.2.0', max_length=64)),
                ('type', models.CharField(choices=[('feature', 'Feature'), ('bugfix', 'Bugfix'), ('improvement', 'Improvement'), ('announcement', 'Announcement')], default='feature', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='', help_text='Markdown-formatted description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Release',
                'verbose_name_plural': 'Platform Releases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformReleaseAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.platform_releases.models.release_attachment_path)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='platform_releases.platformrelease')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_release_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='platformrelease',
            index=models.Index(fields=['status', '-published_at'], name='platform_re_status_b23770_idx'),
        ),
    ]
