http:
  routers:
    api-router:
      rule: 'Host(`{{ env "DOMAIN" }}`) && (PathPrefix(`/api`) || PathPrefix(`/_allauth`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/media`) || PathPrefix(`/accounts`))'
      service: "web-service"
      entryPoints:
        - websecure
      priority: 100
      tls:
        certResolver: letsencrypt

    frontend-router:
      rule: 'Host(`{{ env "DOMAIN" }}`)'
      service: "frontend-service"
      entryPoints:
        - websecure
      priority: 1
      tls:
        certResolver: letsencrypt

  services:
    web-service:
      loadBalancer:
        servers:
          - url: "http://django_prod_container:8000"

    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend_prod_container:80"
