http:
  routers:
    web-router:
      rule: 'Host(`api.{{ env "DOMAIN" }}`)'
      service: "web-service"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    frontend-router:
      rule: 'Host(`{{ env "DOMAIN" }}`)'
      service: "frontend-service"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    web-service:
      loadBalancer:
        servers:
          - url: "http://django_prod_container:8000"

    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend_prod_container:80"
