/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecuredRouteRouteImport } from './routes/_secured/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecuredWhatsNewRouteImport } from './routes/_secured/whats-new'
import { Route as SecuredNotificationsRouteImport } from './routes/_secured/notifications'
import { Route as SecuredDashboardRouteImport } from './routes/_secured/dashboard'
import { Route as SecuredTenantRouteRouteImport } from './routes/_secured/tenant/route'
import { Route as SecuredPlatformRouteRouteImport } from './routes/_secured/platform/route'
import { Route as SecuredAssetsRouteRouteImport } from './routes/_secured/assets/route'
import { Route as SecuredAssetsIndexRouteImport } from './routes/_secured/assets/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as SecuredTenantUsersRouteImport } from './routes/_secured/tenant/users'
import { Route as SecuredPlatformUsersRouteImport } from './routes/_secured/platform/users'
import { Route as SecuredPlatformTenantsRouteImport } from './routes/_secured/platform/tenants'
import { Route as SecuredPlatformSettingsRouteImport } from './routes/_secured/platform/settings'
import { Route as SecuredPlatformReleasesRouteImport } from './routes/_secured/platform/releases'
import { Route as SecuredAssetsTypesRouteImport } from './routes/_secured/assets/types'
import { Route as SecuredAccountTotpSetupRouteImport } from './routes/_secured/account/totp-setup'
import { Route as SecuredAccountPasswordRouteImport } from './routes/_secured/account/password'
import { Route as SecuredAccountEmailRouteImport } from './routes/_secured/account/email'
import { Route as SecuredAccountAuthenticatorsRouteImport } from './routes/_secured/account/authenticators'
import { Route as AuthAuthReauthenticateRouteImport } from './routes/_auth/auth/reauthenticate'
import { Route as AuthAccountProvidersRouteImport } from './routes/_auth/account/providers'
import { Route as SecuredPlatformTenantsIndexRouteImport } from './routes/_secured/platform/tenants.index'
import { Route as AuthRegisterPasskeyIndexRouteImport } from './routes/_auth/register/passkey/index'
import { Route as AuthLoginCodeIndexRouteImport } from './routes/_auth/login/code/index'
import { Route as SecuredPlatformTenantsSlugRouteImport } from './routes/_secured/platform/tenants.$slug'
import { Route as AuthRegisterPasskeyCreateRouteImport } from './routes/_auth/register/passkey/create'
import { Route as AuthLoginCodeConfirmRouteImport } from './routes/_auth/login/code/confirm'
import { Route as AuthAuthPasswordResetRouteImport } from './routes/_auth/auth/password/reset'
import { Route as AuthAuthPasswordRequestRouteImport } from './routes/_auth/auth/password/request'
import { Route as AuthAuthMfaRecoveryCodesRouteImport } from './routes/_auth/auth/mfa/recovery-codes'
import { Route as AuthAuthMfaAuthenticateRouteImport } from './routes/_auth/auth/mfa/authenticate'
import { Route as AuthAuthEmailVerifyRouteImport } from './routes/_auth/auth/email/verify'
import { Route as AuthAccountProviderSignupRouteImport } from './routes/_auth/account/provider/signup'
import { Route as AuthAccountProviderCallbackRouteImport } from './routes/_auth/account/provider/callback'
import { Route as AuthAuthPasswordConfirmKeyRouteImport } from './routes/_auth/auth/password/confirm.$key'
import { Route as AuthAuthEmailConfirmKeyRouteImport } from './routes/_auth/auth/email/confirm.$key'

const SecuredRouteRoute = SecuredRouteRouteImport.update({
  id: '/_secured',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuredWhatsNewRoute = SecuredWhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => SecuredRouteRoute,
} as any)
const SecuredNotificationsRoute = SecuredNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SecuredRouteRoute,
} as any)
const SecuredDashboardRoute = SecuredDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SecuredRouteRoute,
} as any)
const SecuredTenantRouteRoute = SecuredTenantRouteRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => SecuredRouteRoute,
} as any)
const SecuredPlatformRouteRoute = SecuredPlatformRouteRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => SecuredRouteRoute,
} as any)
const SecuredAssetsRouteRoute = SecuredAssetsRouteRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => SecuredRouteRoute,
} as any)
const SecuredAssetsIndexRoute = SecuredAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecuredAssetsRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SecuredTenantUsersRoute = SecuredTenantUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SecuredTenantRouteRoute,
} as any)
const SecuredPlatformUsersRoute = SecuredPlatformUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SecuredPlatformRouteRoute,
} as any)
const SecuredPlatformTenantsRoute = SecuredPlatformTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => SecuredPlatformRouteRoute,
} as any)
const SecuredPlatformSettingsRoute = SecuredPlatformSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SecuredPlatformRouteRoute,
} as any)
const SecuredPlatformReleasesRoute = SecuredPlatformReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => SecuredPlatformRouteRoute,
} as any)
const SecuredAssetsTypesRoute = SecuredAssetsTypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => SecuredAssetsRouteRoute,
} as any)
const SecuredAccountTotpSetupRoute = SecuredAccountTotpSetupRouteImport.update({
  id: '/account/totp-setup',
  path: '/account/totp-setup',
  getParentRoute: () => SecuredRouteRoute,
} as any)
const SecuredAccountPasswordRoute = SecuredAccountPasswordRouteImport.update({
  id: '/account/password',
  path: '/account/password',
  getParentRoute: () => SecuredRouteRoute,
} as any)
const SecuredAccountEmailRoute = SecuredAccountEmailRouteImport.update({
  id: '/account/email',
  path: '/account/email',
  getParentRoute: () => SecuredRouteRoute,
} as any)
const SecuredAccountAuthenticatorsRoute =
  SecuredAccountAuthenticatorsRouteImport.update({
    id: '/account/authenticators',
    path: '/account/authenticators',
    getParentRoute: () => SecuredRouteRoute,
  } as any)
const AuthAuthReauthenticateRoute = AuthAuthReauthenticateRouteImport.update({
  id: '/auth/reauthenticate',
  path: '/auth/reauthenticate',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAccountProvidersRoute = AuthAccountProvidersRouteImport.update({
  id: '/account/providers',
  path: '/account/providers',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SecuredPlatformTenantsIndexRoute =
  SecuredPlatformTenantsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SecuredPlatformTenantsRoute,
  } as any)
const AuthRegisterPasskeyIndexRoute =
  AuthRegisterPasskeyIndexRouteImport.update({
    id: '/register/passkey/',
    path: '/register/passkey/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthLoginCodeIndexRoute = AuthLoginCodeIndexRouteImport.update({
  id: '/login/code/',
  path: '/login/code/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SecuredPlatformTenantsSlugRoute =
  SecuredPlatformTenantsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => SecuredPlatformTenantsRoute,
  } as any)
const AuthRegisterPasskeyCreateRoute =
  AuthRegisterPasskeyCreateRouteImport.update({
    id: '/register/passkey/create',
    path: '/register/passkey/create',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthLoginCodeConfirmRoute = AuthLoginCodeConfirmRouteImport.update({
  id: '/login/code/confirm',
  path: '/login/code/confirm',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthPasswordResetRoute = AuthAuthPasswordResetRouteImport.update({
  id: '/auth/password/reset',
  path: '/auth/password/reset',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthPasswordRequestRoute = AuthAuthPasswordRequestRouteImport.update({
  id: '/auth/password/request',
  path: '/auth/password/request',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthMfaRecoveryCodesRoute =
  AuthAuthMfaRecoveryCodesRouteImport.update({
    id: '/auth/mfa/recovery-codes',
    path: '/auth/mfa/recovery-codes',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAuthMfaAuthenticateRoute = AuthAuthMfaAuthenticateRouteImport.update({
  id: '/auth/mfa/authenticate',
  path: '/auth/mfa/authenticate',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthEmailVerifyRoute = AuthAuthEmailVerifyRouteImport.update({
  id: '/auth/email/verify',
  path: '/auth/email/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAccountProviderSignupRoute =
  AuthAccountProviderSignupRouteImport.update({
    id: '/account/provider/signup',
    path: '/account/provider/signup',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAccountProviderCallbackRoute =
  AuthAccountProviderCallbackRouteImport.update({
    id: '/account/provider/callback',
    path: '/account/provider/callback',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAuthPasswordConfirmKeyRoute =
  AuthAuthPasswordConfirmKeyRouteImport.update({
    id: '/auth/password/confirm/$key',
    path: '/auth/password/confirm/$key',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAuthEmailConfirmKeyRoute = AuthAuthEmailConfirmKeyRouteImport.update({
  id: '/auth/email/confirm/$key',
  path: '/auth/email/confirm/$key',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof SecuredAssetsRouteRouteWithChildren
  '/platform': typeof SecuredPlatformRouteRouteWithChildren
  '/tenant': typeof SecuredTenantRouteRouteWithChildren
  '/dashboard': typeof SecuredDashboardRoute
  '/notifications': typeof SecuredNotificationsRoute
  '/whats-new': typeof SecuredWhatsNewRoute
  '/account/providers': typeof AuthAccountProvidersRoute
  '/auth/reauthenticate': typeof AuthAuthReauthenticateRoute
  '/account/authenticators': typeof SecuredAccountAuthenticatorsRoute
  '/account/email': typeof SecuredAccountEmailRoute
  '/account/password': typeof SecuredAccountPasswordRoute
  '/account/totp-setup': typeof SecuredAccountTotpSetupRoute
  '/assets/types': typeof SecuredAssetsTypesRoute
  '/platform/releases': typeof SecuredPlatformReleasesRoute
  '/platform/settings': typeof SecuredPlatformSettingsRoute
  '/platform/tenants': typeof SecuredPlatformTenantsRouteWithChildren
  '/platform/users': typeof SecuredPlatformUsersRoute
  '/tenant/users': typeof SecuredTenantUsersRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/assets/': typeof SecuredAssetsIndexRoute
  '/account/provider/callback': typeof AuthAccountProviderCallbackRoute
  '/account/provider/signup': typeof AuthAccountProviderSignupRoute
  '/auth/email/verify': typeof AuthAuthEmailVerifyRoute
  '/auth/mfa/authenticate': typeof AuthAuthMfaAuthenticateRoute
  '/auth/mfa/recovery-codes': typeof AuthAuthMfaRecoveryCodesRoute
  '/auth/password/request': typeof AuthAuthPasswordRequestRoute
  '/auth/password/reset': typeof AuthAuthPasswordResetRoute
  '/login/code/confirm': typeof AuthLoginCodeConfirmRoute
  '/register/passkey/create': typeof AuthRegisterPasskeyCreateRoute
  '/platform/tenants/$slug': typeof SecuredPlatformTenantsSlugRoute
  '/login/code': typeof AuthLoginCodeIndexRoute
  '/register/passkey': typeof AuthRegisterPasskeyIndexRoute
  '/platform/tenants/': typeof SecuredPlatformTenantsIndexRoute
  '/auth/email/confirm/$key': typeof AuthAuthEmailConfirmKeyRoute
  '/auth/password/confirm/$key': typeof AuthAuthPasswordConfirmKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/platform': typeof SecuredPlatformRouteRouteWithChildren
  '/tenant': typeof SecuredTenantRouteRouteWithChildren
  '/dashboard': typeof SecuredDashboardRoute
  '/notifications': typeof SecuredNotificationsRoute
  '/whats-new': typeof SecuredWhatsNewRoute
  '/account/providers': typeof AuthAccountProvidersRoute
  '/auth/reauthenticate': typeof AuthAuthReauthenticateRoute
  '/account/authenticators': typeof SecuredAccountAuthenticatorsRoute
  '/account/email': typeof SecuredAccountEmailRoute
  '/account/password': typeof SecuredAccountPasswordRoute
  '/account/totp-setup': typeof SecuredAccountTotpSetupRoute
  '/assets/types': typeof SecuredAssetsTypesRoute
  '/platform/releases': typeof SecuredPlatformReleasesRoute
  '/platform/settings': typeof SecuredPlatformSettingsRoute
  '/platform/users': typeof SecuredPlatformUsersRoute
  '/tenant/users': typeof SecuredTenantUsersRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/assets': typeof SecuredAssetsIndexRoute
  '/account/provider/callback': typeof AuthAccountProviderCallbackRoute
  '/account/provider/signup': typeof AuthAccountProviderSignupRoute
  '/auth/email/verify': typeof AuthAuthEmailVerifyRoute
  '/auth/mfa/authenticate': typeof AuthAuthMfaAuthenticateRoute
  '/auth/mfa/recovery-codes': typeof AuthAuthMfaRecoveryCodesRoute
  '/auth/password/request': typeof AuthAuthPasswordRequestRoute
  '/auth/password/reset': typeof AuthAuthPasswordResetRoute
  '/login/code/confirm': typeof AuthLoginCodeConfirmRoute
  '/register/passkey/create': typeof AuthRegisterPasskeyCreateRoute
  '/platform/tenants/$slug': typeof SecuredPlatformTenantsSlugRoute
  '/login/code': typeof AuthLoginCodeIndexRoute
  '/register/passkey': typeof AuthRegisterPasskeyIndexRoute
  '/platform/tenants': typeof SecuredPlatformTenantsIndexRoute
  '/auth/email/confirm/$key': typeof AuthAuthEmailConfirmKeyRoute
  '/auth/password/confirm/$key': typeof AuthAuthPasswordConfirmKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_secured': typeof SecuredRouteRouteWithChildren
  '/_secured/assets': typeof SecuredAssetsRouteRouteWithChildren
  '/_secured/platform': typeof SecuredPlatformRouteRouteWithChildren
  '/_secured/tenant': typeof SecuredTenantRouteRouteWithChildren
  '/_secured/dashboard': typeof SecuredDashboardRoute
  '/_secured/notifications': typeof SecuredNotificationsRoute
  '/_secured/whats-new': typeof SecuredWhatsNewRoute
  '/_auth/account/providers': typeof AuthAccountProvidersRoute
  '/_auth/auth/reauthenticate': typeof AuthAuthReauthenticateRoute
  '/_secured/account/authenticators': typeof SecuredAccountAuthenticatorsRoute
  '/_secured/account/email': typeof SecuredAccountEmailRoute
  '/_secured/account/password': typeof SecuredAccountPasswordRoute
  '/_secured/account/totp-setup': typeof SecuredAccountTotpSetupRoute
  '/_secured/assets/types': typeof SecuredAssetsTypesRoute
  '/_secured/platform/releases': typeof SecuredPlatformReleasesRoute
  '/_secured/platform/settings': typeof SecuredPlatformSettingsRoute
  '/_secured/platform/tenants': typeof SecuredPlatformTenantsRouteWithChildren
  '/_secured/platform/users': typeof SecuredPlatformUsersRoute
  '/_secured/tenant/users': typeof SecuredTenantUsersRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_secured/assets/': typeof SecuredAssetsIndexRoute
  '/_auth/account/provider/callback': typeof AuthAccountProviderCallbackRoute
  '/_auth/account/provider/signup': typeof AuthAccountProviderSignupRoute
  '/_auth/auth/email/verify': typeof AuthAuthEmailVerifyRoute
  '/_auth/auth/mfa/authenticate': typeof AuthAuthMfaAuthenticateRoute
  '/_auth/auth/mfa/recovery-codes': typeof AuthAuthMfaRecoveryCodesRoute
  '/_auth/auth/password/request': typeof AuthAuthPasswordRequestRoute
  '/_auth/auth/password/reset': typeof AuthAuthPasswordResetRoute
  '/_auth/login/code/confirm': typeof AuthLoginCodeConfirmRoute
  '/_auth/register/passkey/create': typeof AuthRegisterPasskeyCreateRoute
  '/_secured/platform/tenants/$slug': typeof SecuredPlatformTenantsSlugRoute
  '/_auth/login/code/': typeof AuthLoginCodeIndexRoute
  '/_auth/register/passkey/': typeof AuthRegisterPasskeyIndexRoute
  '/_secured/platform/tenants/': typeof SecuredPlatformTenantsIndexRoute
  '/_auth/auth/email/confirm/$key': typeof AuthAuthEmailConfirmKeyRoute
  '/_auth/auth/password/confirm/$key': typeof AuthAuthPasswordConfirmKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/platform'
    | '/tenant'
    | '/dashboard'
    | '/notifications'
    | '/whats-new'
    | '/account/providers'
    | '/auth/reauthenticate'
    | '/account/authenticators'
    | '/account/email'
    | '/account/password'
    | '/account/totp-setup'
    | '/assets/types'
    | '/platform/releases'
    | '/platform/settings'
    | '/platform/tenants'
    | '/platform/users'
    | '/tenant/users'
    | '/login'
    | '/register'
    | '/assets/'
    | '/account/provider/callback'
    | '/account/provider/signup'
    | '/auth/email/verify'
    | '/auth/mfa/authenticate'
    | '/auth/mfa/recovery-codes'
    | '/auth/password/request'
    | '/auth/password/reset'
    | '/login/code/confirm'
    | '/register/passkey/create'
    | '/platform/tenants/$slug'
    | '/login/code'
    | '/register/passkey'
    | '/platform/tenants/'
    | '/auth/email/confirm/$key'
    | '/auth/password/confirm/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/platform'
    | '/tenant'
    | '/dashboard'
    | '/notifications'
    | '/whats-new'
    | '/account/providers'
    | '/auth/reauthenticate'
    | '/account/authenticators'
    | '/account/email'
    | '/account/password'
    | '/account/totp-setup'
    | '/assets/types'
    | '/platform/releases'
    | '/platform/settings'
    | '/platform/users'
    | '/tenant/users'
    | '/login'
    | '/register'
    | '/assets'
    | '/account/provider/callback'
    | '/account/provider/signup'
    | '/auth/email/verify'
    | '/auth/mfa/authenticate'
    | '/auth/mfa/recovery-codes'
    | '/auth/password/request'
    | '/auth/password/reset'
    | '/login/code/confirm'
    | '/register/passkey/create'
    | '/platform/tenants/$slug'
    | '/login/code'
    | '/register/passkey'
    | '/platform/tenants'
    | '/auth/email/confirm/$key'
    | '/auth/password/confirm/$key'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_secured'
    | '/_secured/assets'
    | '/_secured/platform'
    | '/_secured/tenant'
    | '/_secured/dashboard'
    | '/_secured/notifications'
    | '/_secured/whats-new'
    | '/_auth/account/providers'
    | '/_auth/auth/reauthenticate'
    | '/_secured/account/authenticators'
    | '/_secured/account/email'
    | '/_secured/account/password'
    | '/_secured/account/totp-setup'
    | '/_secured/assets/types'
    | '/_secured/platform/releases'
    | '/_secured/platform/settings'
    | '/_secured/platform/tenants'
    | '/_secured/platform/users'
    | '/_secured/tenant/users'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_secured/assets/'
    | '/_auth/account/provider/callback'
    | '/_auth/account/provider/signup'
    | '/_auth/auth/email/verify'
    | '/_auth/auth/mfa/authenticate'
    | '/_auth/auth/mfa/recovery-codes'
    | '/_auth/auth/password/request'
    | '/_auth/auth/password/reset'
    | '/_auth/login/code/confirm'
    | '/_auth/register/passkey/create'
    | '/_secured/platform/tenants/$slug'
    | '/_auth/login/code/'
    | '/_auth/register/passkey/'
    | '/_secured/platform/tenants/'
    | '/_auth/auth/email/confirm/$key'
    | '/_auth/auth/password/confirm/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SecuredRouteRoute: typeof SecuredRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_secured': {
      id: '/_secured'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SecuredRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_secured/whats-new': {
      id: '/_secured/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof SecuredWhatsNewRouteImport
      parentRoute: typeof SecuredRouteRoute
    }
    '/_secured/notifications': {
      id: '/_secured/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof SecuredNotificationsRouteImport
      parentRoute: typeof SecuredRouteRoute
    }
    '/_secured/dashboard': {
      id: '/_secured/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SecuredDashboardRouteImport
      parentRoute: typeof SecuredRouteRoute
    }
    '/_secured/tenant': {
      id: '/_secured/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof SecuredTenantRouteRouteImport
      parentRoute: typeof SecuredRouteRoute
    }
    '/_secured/platform': {
      id: '/_secured/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof SecuredPlatformRouteRouteImport
      parentRoute: typeof SecuredRouteRoute
    }
    '/_secured/assets': {
      id: '/_secured/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof SecuredAssetsRouteRouteImport
      parentRoute: typeof SecuredRouteRoute
    }
    '/_secured/assets/': {
      id: '/_secured/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof SecuredAssetsIndexRouteImport
      parentRoute: typeof SecuredAssetsRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_secured/tenant/users': {
      id: '/_secured/tenant/users'
      path: '/users'
      fullPath: '/tenant/users'
      preLoaderRoute: typeof SecuredTenantUsersRouteImport
      parentRoute: typeof SecuredTenantRouteRoute
    }
    '/_secured/platform/users': {
      id: '/_secured/platform/users'
      path: '/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof SecuredPlatformUsersRouteImport
      parentRoute: typeof SecuredPlatformRouteRoute
    }
    '/_secured/platform/tenants': {
      id: '/_secured/platform/tenants'
      path: '/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof SecuredPlatformTenantsRouteImport
      parentRoute: typeof SecuredPlatformRouteRoute
    }
    '/_secured/platform/settings': {
      id: '/_secured/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof SecuredPlatformSettingsRouteImport
      parentRoute: typeof SecuredPlatformRouteRoute
    }
    '/_secured/platform/releases': {
      id: '/_secured/platform/releases'
      path: '/releases'
      fullPath: '/platform/releases'
      preLoaderRoute: typeof SecuredPlatformReleasesRouteImport
      parentRoute: typeof SecuredPlatformRouteRoute
    }
    '/_secured/assets/types': {
      id: '/_secured/assets/types'
      path: '/types'
      fullPath: '/assets/types'
      preLoaderRoute: typeof SecuredAssetsTypesRouteImport
      parentRoute: typeof SecuredAssetsRouteRoute
    }
    '/_secured/account/totp-setup': {
      id: '/_secured/account/totp-setup'
      path: '/account/totp-setup'
      fullPath: '/account/totp-setup'
      preLoaderRoute: typeof SecuredAccountTotpSetupRouteImport
      parentRoute: typeof SecuredRouteRoute
    }
    '/_secured/account/password': {
      id: '/_secured/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof SecuredAccountPasswordRouteImport
      parentRoute: typeof SecuredRouteRoute
    }
    '/_secured/account/email': {
      id: '/_secured/account/email'
      path: '/account/email'
      fullPath: '/account/email'
      preLoaderRoute: typeof SecuredAccountEmailRouteImport
      parentRoute: typeof SecuredRouteRoute
    }
    '/_secured/account/authenticators': {
      id: '/_secured/account/authenticators'
      path: '/account/authenticators'
      fullPath: '/account/authenticators'
      preLoaderRoute: typeof SecuredAccountAuthenticatorsRouteImport
      parentRoute: typeof SecuredRouteRoute
    }
    '/_auth/auth/reauthenticate': {
      id: '/_auth/auth/reauthenticate'
      path: '/auth/reauthenticate'
      fullPath: '/auth/reauthenticate'
      preLoaderRoute: typeof AuthAuthReauthenticateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/account/providers': {
      id: '/_auth/account/providers'
      path: '/account/providers'
      fullPath: '/account/providers'
      preLoaderRoute: typeof AuthAccountProvidersRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_secured/platform/tenants/': {
      id: '/_secured/platform/tenants/'
      path: '/'
      fullPath: '/platform/tenants/'
      preLoaderRoute: typeof SecuredPlatformTenantsIndexRouteImport
      parentRoute: typeof SecuredPlatformTenantsRoute
    }
    '/_auth/register/passkey/': {
      id: '/_auth/register/passkey/'
      path: '/register/passkey'
      fullPath: '/register/passkey'
      preLoaderRoute: typeof AuthRegisterPasskeyIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/code/': {
      id: '/_auth/login/code/'
      path: '/login/code'
      fullPath: '/login/code'
      preLoaderRoute: typeof AuthLoginCodeIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_secured/platform/tenants/$slug': {
      id: '/_secured/platform/tenants/$slug'
      path: '/$slug'
      fullPath: '/platform/tenants/$slug'
      preLoaderRoute: typeof SecuredPlatformTenantsSlugRouteImport
      parentRoute: typeof SecuredPlatformTenantsRoute
    }
    '/_auth/register/passkey/create': {
      id: '/_auth/register/passkey/create'
      path: '/register/passkey/create'
      fullPath: '/register/passkey/create'
      preLoaderRoute: typeof AuthRegisterPasskeyCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/code/confirm': {
      id: '/_auth/login/code/confirm'
      path: '/login/code/confirm'
      fullPath: '/login/code/confirm'
      preLoaderRoute: typeof AuthLoginCodeConfirmRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/password/reset': {
      id: '/_auth/auth/password/reset'
      path: '/auth/password/reset'
      fullPath: '/auth/password/reset'
      preLoaderRoute: typeof AuthAuthPasswordResetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/password/request': {
      id: '/_auth/auth/password/request'
      path: '/auth/password/request'
      fullPath: '/auth/password/request'
      preLoaderRoute: typeof AuthAuthPasswordRequestRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/mfa/recovery-codes': {
      id: '/_auth/auth/mfa/recovery-codes'
      path: '/auth/mfa/recovery-codes'
      fullPath: '/auth/mfa/recovery-codes'
      preLoaderRoute: typeof AuthAuthMfaRecoveryCodesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/mfa/authenticate': {
      id: '/_auth/auth/mfa/authenticate'
      path: '/auth/mfa/authenticate'
      fullPath: '/auth/mfa/authenticate'
      preLoaderRoute: typeof AuthAuthMfaAuthenticateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/email/verify': {
      id: '/_auth/auth/email/verify'
      path: '/auth/email/verify'
      fullPath: '/auth/email/verify'
      preLoaderRoute: typeof AuthAuthEmailVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/account/provider/signup': {
      id: '/_auth/account/provider/signup'
      path: '/account/provider/signup'
      fullPath: '/account/provider/signup'
      preLoaderRoute: typeof AuthAccountProviderSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/account/provider/callback': {
      id: '/_auth/account/provider/callback'
      path: '/account/provider/callback'
      fullPath: '/account/provider/callback'
      preLoaderRoute: typeof AuthAccountProviderCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/password/confirm/$key': {
      id: '/_auth/auth/password/confirm/$key'
      path: '/auth/password/confirm/$key'
      fullPath: '/auth/password/confirm/$key'
      preLoaderRoute: typeof AuthAuthPasswordConfirmKeyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/email/confirm/$key': {
      id: '/_auth/auth/email/confirm/$key'
      path: '/auth/email/confirm/$key'
      fullPath: '/auth/email/confirm/$key'
      preLoaderRoute: typeof AuthAuthEmailConfirmKeyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAccountProvidersRoute: typeof AuthAccountProvidersRoute
  AuthAuthReauthenticateRoute: typeof AuthAuthReauthenticateRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthAccountProviderCallbackRoute: typeof AuthAccountProviderCallbackRoute
  AuthAccountProviderSignupRoute: typeof AuthAccountProviderSignupRoute
  AuthAuthEmailVerifyRoute: typeof AuthAuthEmailVerifyRoute
  AuthAuthMfaAuthenticateRoute: typeof AuthAuthMfaAuthenticateRoute
  AuthAuthMfaRecoveryCodesRoute: typeof AuthAuthMfaRecoveryCodesRoute
  AuthAuthPasswordRequestRoute: typeof AuthAuthPasswordRequestRoute
  AuthAuthPasswordResetRoute: typeof AuthAuthPasswordResetRoute
  AuthLoginCodeConfirmRoute: typeof AuthLoginCodeConfirmRoute
  AuthRegisterPasskeyCreateRoute: typeof AuthRegisterPasskeyCreateRoute
  AuthLoginCodeIndexRoute: typeof AuthLoginCodeIndexRoute
  AuthRegisterPasskeyIndexRoute: typeof AuthRegisterPasskeyIndexRoute
  AuthAuthEmailConfirmKeyRoute: typeof AuthAuthEmailConfirmKeyRoute
  AuthAuthPasswordConfirmKeyRoute: typeof AuthAuthPasswordConfirmKeyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAccountProvidersRoute: AuthAccountProvidersRoute,
  AuthAuthReauthenticateRoute: AuthAuthReauthenticateRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthAccountProviderCallbackRoute: AuthAccountProviderCallbackRoute,
  AuthAccountProviderSignupRoute: AuthAccountProviderSignupRoute,
  AuthAuthEmailVerifyRoute: AuthAuthEmailVerifyRoute,
  AuthAuthMfaAuthenticateRoute: AuthAuthMfaAuthenticateRoute,
  AuthAuthMfaRecoveryCodesRoute: AuthAuthMfaRecoveryCodesRoute,
  AuthAuthPasswordRequestRoute: AuthAuthPasswordRequestRoute,
  AuthAuthPasswordResetRoute: AuthAuthPasswordResetRoute,
  AuthLoginCodeConfirmRoute: AuthLoginCodeConfirmRoute,
  AuthRegisterPasskeyCreateRoute: AuthRegisterPasskeyCreateRoute,
  AuthLoginCodeIndexRoute: AuthLoginCodeIndexRoute,
  AuthRegisterPasskeyIndexRoute: AuthRegisterPasskeyIndexRoute,
  AuthAuthEmailConfirmKeyRoute: AuthAuthEmailConfirmKeyRoute,
  AuthAuthPasswordConfirmKeyRoute: AuthAuthPasswordConfirmKeyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SecuredAssetsRouteRouteChildren {
  SecuredAssetsTypesRoute: typeof SecuredAssetsTypesRoute
  SecuredAssetsIndexRoute: typeof SecuredAssetsIndexRoute
}

const SecuredAssetsRouteRouteChildren: SecuredAssetsRouteRouteChildren = {
  SecuredAssetsTypesRoute: SecuredAssetsTypesRoute,
  SecuredAssetsIndexRoute: SecuredAssetsIndexRoute,
}

const SecuredAssetsRouteRouteWithChildren =
  SecuredAssetsRouteRoute._addFileChildren(SecuredAssetsRouteRouteChildren)

interface SecuredPlatformTenantsRouteChildren {
  SecuredPlatformTenantsSlugRoute: typeof SecuredPlatformTenantsSlugRoute
  SecuredPlatformTenantsIndexRoute: typeof SecuredPlatformTenantsIndexRoute
}

const SecuredPlatformTenantsRouteChildren: SecuredPlatformTenantsRouteChildren =
  {
    SecuredPlatformTenantsSlugRoute: SecuredPlatformTenantsSlugRoute,
    SecuredPlatformTenantsIndexRoute: SecuredPlatformTenantsIndexRoute,
  }

const SecuredPlatformTenantsRouteWithChildren =
  SecuredPlatformTenantsRoute._addFileChildren(
    SecuredPlatformTenantsRouteChildren,
  )

interface SecuredPlatformRouteRouteChildren {
  SecuredPlatformReleasesRoute: typeof SecuredPlatformReleasesRoute
  SecuredPlatformSettingsRoute: typeof SecuredPlatformSettingsRoute
  SecuredPlatformTenantsRoute: typeof SecuredPlatformTenantsRouteWithChildren
  SecuredPlatformUsersRoute: typeof SecuredPlatformUsersRoute
}

const SecuredPlatformRouteRouteChildren: SecuredPlatformRouteRouteChildren = {
  SecuredPlatformReleasesRoute: SecuredPlatformReleasesRoute,
  SecuredPlatformSettingsRoute: SecuredPlatformSettingsRoute,
  SecuredPlatformTenantsRoute: SecuredPlatformTenantsRouteWithChildren,
  SecuredPlatformUsersRoute: SecuredPlatformUsersRoute,
}

const SecuredPlatformRouteRouteWithChildren =
  SecuredPlatformRouteRoute._addFileChildren(SecuredPlatformRouteRouteChildren)

interface SecuredTenantRouteRouteChildren {
  SecuredTenantUsersRoute: typeof SecuredTenantUsersRoute
}

const SecuredTenantRouteRouteChildren: SecuredTenantRouteRouteChildren = {
  SecuredTenantUsersRoute: SecuredTenantUsersRoute,
}

const SecuredTenantRouteRouteWithChildren =
  SecuredTenantRouteRoute._addFileChildren(SecuredTenantRouteRouteChildren)

interface SecuredRouteRouteChildren {
  SecuredAssetsRouteRoute: typeof SecuredAssetsRouteRouteWithChildren
  SecuredPlatformRouteRoute: typeof SecuredPlatformRouteRouteWithChildren
  SecuredTenantRouteRoute: typeof SecuredTenantRouteRouteWithChildren
  SecuredDashboardRoute: typeof SecuredDashboardRoute
  SecuredNotificationsRoute: typeof SecuredNotificationsRoute
  SecuredWhatsNewRoute: typeof SecuredWhatsNewRoute
  SecuredAccountAuthenticatorsRoute: typeof SecuredAccountAuthenticatorsRoute
  SecuredAccountEmailRoute: typeof SecuredAccountEmailRoute
  SecuredAccountPasswordRoute: typeof SecuredAccountPasswordRoute
  SecuredAccountTotpSetupRoute: typeof SecuredAccountTotpSetupRoute
}

const SecuredRouteRouteChildren: SecuredRouteRouteChildren = {
  SecuredAssetsRouteRoute: SecuredAssetsRouteRouteWithChildren,
  SecuredPlatformRouteRoute: SecuredPlatformRouteRouteWithChildren,
  SecuredTenantRouteRoute: SecuredTenantRouteRouteWithChildren,
  SecuredDashboardRoute: SecuredDashboardRoute,
  SecuredNotificationsRoute: SecuredNotificationsRoute,
  SecuredWhatsNewRoute: SecuredWhatsNewRoute,
  SecuredAccountAuthenticatorsRoute: SecuredAccountAuthenticatorsRoute,
  SecuredAccountEmailRoute: SecuredAccountEmailRoute,
  SecuredAccountPasswordRoute: SecuredAccountPasswordRoute,
  SecuredAccountTotpSetupRoute: SecuredAccountTotpSetupRoute,
}

const SecuredRouteRouteWithChildren = SecuredRouteRoute._addFileChildren(
  SecuredRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SecuredRouteRoute: SecuredRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
