# Generated by Django 5.2.10 on 2026-01-25 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '__first__'),
        ('user', '0003_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], default='tr', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('tenant_admin', 'Tenant Admin'), ('tenant_user', 'Tenant User')], default='tenant_user', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant this user belongs to. Null for platform admins.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.tenant'),
        ),
    ]
